package com.art.drinkgpt.models.dto;

import lombok.Data;

@Data
public class SuggestedDrinkDTO {
    // Name of the suggested drink
    private String name;
    
    // Short description of the drink
    private String description;
    
    // Ingredients as a String
    private String ingredients;
    
    // Detailed recipe generated by AI
    private String recipe;
} 