spring:
  application:
    name: DrinkGPT
  datasource:
    url: jdbc:h2:mem:drinkdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
  h2:
    console:
      enabled: true
      path: /h2-console
  ai:
    openai:
      api-key: ${OPENROUTER_API_KEY}
      base-url: https://openrouter.ai/api/
      chat:
        options:
          model: google/gemini-2.0-flash-001
          temperature: 0.7
